{
 "title": "Sysdig Agent troubleshooting",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "query": {
     "query": "label_values(kube_cluster_name)"
    }
   },
   { "name": "datasource", "query": "prometheus" },
   { "name": "program", "query": { "query": "label_values(program_name)" } },
   { "name": "pod", "query": { "query": "label_values(kube_pod_name)" } },
   { "name": "node", "query": { "query": "label_values(kube_node_name)" } }
  ]
 },
 "panels": [
  {
   "title": "Avg CPU by Pod",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "avg by (kube_pod_name, kube_node_name)(sysdig_container_cpu_cores_used{kube_cluster_name=~\"$cluster\", kube_pod_name=~\"$pod\", kube_node_name=~\"$node\", kube_workload_name=\"sysdig-agent\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "topk(1, sum by (kube_pod_name)(kube_pod_container_resource_limits{kube_cluster_name=~\"$cluster\", kube_workload_name=\"sysdig-agent\", resource=\"cpu\"}))",
     "legendFormat": "CPU Limit"
    }
   ]
  },
  {
   "title": "Avg CPU by Program",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "avg by (kube_node_name, kube_pod_name, program_name)(sysdig_program_cpu_cores_used{kube_cluster_name=~\"$cluster\", kube_pod_name=~\"$pod\", kube_node_name=~\"$node\",kube_workload_name=\"sysdig-agent\", program_name=~\"$program\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Avg Memory by Pod",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "avg by (kube_pod_name, kube_node_name)(sysdig_container_memory_used_bytes{kube_cluster_name=~\"$cluster\", kube_pod_name=~\"$pod\", kube_node_name=~\"$node\", kube_workload_name=\"sysdig-agent\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "topk(1, sum by (kube_pod_name)(kube_pod_container_resource_limits{kube_cluster_name=~\"$cluster\", kube_workload_name=\"sysdig-agent\", resource=\"memory\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Avg Memory by Program",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "avg by (kube_node_name, kube_pod_name, program_name)(sysdig_program_memory_used_bytes{kube_cluster_name=~\"$cluster\", kube_pod_name=~\"$pod\", kube_node_name=~\"$node\", kube_workload_name=\"sysdig-agent\", program_name=~\"$program\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Max CPU by Pod",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 31 },
   "targets": [
    {
     "expr": "max by (kube_pod_name, kube_node_name)(sysdig_container_cpu_cores_used{kube_cluster_name=~\"$cluster\", kube_node_name=~\"$node\", kube_pod_name=~\"$pod\", kube_workload_name=\"sysdig-agent\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "topk(1, sum by (kube_pod_name)(kube_pod_container_resource_limits{kube_cluster_name=~\"$cluster\", kube_workload_name=\"sysdig-agent\", resource=\"cpu\"}))",
     "legendFormat": "CPU Limit"
    }
   ]
  },
  {
   "title": "Max CPU by Program",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 31 },
   "targets": [
    {
     "expr": "max by (kube_node_name, kube_pod_name, program_name)(sysdig_program_cpu_cores_used{kube_cluster_name=~\"$cluster\", kube_pod_name=~\"$pod\", kube_node_name=~\"$node\", kube_workload_name=\"sysdig-agent\", program_name=~\"$program\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Max Memory by Pod",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "max by (kube_pod_name, kube_node_name)(sysdig_container_memory_used_bytes{kube_cluster_name=~\"$cluster\", kube_node_name=~\"$node\", kube_pod_name=~\"$pod\", kube_workload_name=\"sysdig-agent\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "topk(1, sum by (kube_pod_name)(kube_pod_container_resource_limits{kube_cluster_name=~\"$cluster\", kube_workload_name=\"sysdig-agent\", resource=\"memory\"}))",
     "legendFormat": "Memory Limit"
    }
   ]
  },
  {
   "title": "Max Memory by Program",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "max by (kube_node_name, kube_pod_name, program_name)(sysdig_program_memory_used_bytes{kube_cluster_name=~\"$cluster\", kube_node_name=~\"$node\", kube_pod_name=~\"$pod\", kube_workload_name=\"sysdig-agent\", program_name=~\"$program\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pods per node",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 63 },
   "targets": [
    {
     "expr": "sum by (kube_node_name)(kube_pod_container_status_running{kube_cluster_name=~\"$cluster\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Container restarts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(kube_pod_name) (kube_pod_sysdig_restart_count{kube_workload_name=\"sysdig-agent\", kube_cluster_name=~\"$cluster\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Node count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 71 },
   "targets": [
    { "expr": "sum(kube_node_sysdig_host)", "legendFormat": "Total node count" },
    {
     "expr": "sum by (kube_cluster_name)(kube_node_sysdig_host{kube_cluster_name=~\"$cluster\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Node capacity - CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 71 },
   "targets": [
    {
     "expr": "sum by (kube_node_name)(kube_node_status_capacity{kube_node_resource=\"cpu\", cluster=~\"$cluster\", kube_node_name=~\"$node\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Node capacity - Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by (kube_node_name)(kube_node_status_capacity{kube_node_resource=\"memory\", cluster=~\"$cluster\", kube_node_name=~\"$node\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}