{
 "title": "ClusterShield metrics",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "Image analysis result",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(analyze_image_result{}[$__interval])) by (status)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "K8s audit - processed events ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by (source) (rate(k8s_audit_ac_events_processed_total{}[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "processed messages by NATS subject ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "processed_messages_success{kube_workload_name =\"sysdig-shield-cluster\"}",
     "legendFormat": "{{type}} - success"
    },
    {
     "expr": "processed_messages_failure{kube_workload_name =\"sysdig-shield-cluster\"}",
     "legendFormat": "{{type}} - failure"
    }
   ]
  },
  {
   "title": "Images-scanned results ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(load_image_result{code =~ \".*\", status =~ \".*\"}[$__interval])) by(code, status)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cache size per cache type",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum(avg_over_time(scanner_analyzer_cache_payload_bytes_sum{}[$__interval])) by (service)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Amount of items per cache type",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "sum(avg_over_time(scanner_analyzer_cache_items_count{}[$__interval])) by (service)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cache hit vs miss ratio",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n  sum(scanner_analyzer_cache_hit_ratio{result=\"hit\"}) \n  /\n  sum(scanner_analyzer_cache_hit_ratio)\n) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}